version: "2"
services:
    product-gallery-manager:
        image: jmgorduez/product-gallery-manager:QA
        container_name: product-gallery-manager
        environment:
        - PORT=8080
        ports:
        - "8080:8080"