version: "2"
services:
    product-gallery-manager:
        image: jmgorduez/product-gallery-manager:560da130058f735993ae8f4fcf7b655f59c94126
        container_name: product-gallery-manager
        environment:
        - PORT=8080
        ports:
        - "8080:8080"
        depends_on:
        - product-gallery