name: Deploy to QA

on:
  push:
    branches: master 

jobs:
  deploy_to_QA_checker:
    name: Deploy to QA checker
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: NPM install -g yarn
      run: sudo npm install -g yarn  

    - name: YARN install
      run: |
        yarn

    - name: Running static code review  
      run: |
        yarn eslint

    - name: Running unit tests  
      run: |
        yarn test

    - name: Running Cypress E2E tests
      uses: cypress-io/github-action@v1
      with:
        start: yarn start:staging
        browser: chrome
        spec: cypress/integration/*.spec.js

    - name: Build app  
      run: |
        yarn build:staging

    - name: Upload app images to the registry
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: jmgorduez/ui-gaming-cards
        tag: "QA"
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: NODE_ENV='staging'
  
  deploy_to_QA:
    name: Upload to AWS QA enviroment
    runs-on: ubuntu-latest
    needs: [deploy_to_QA_checker]

    steps:
    - name: Deploy app to AWS
      uses: appleboy/ssh-action@master
      env: 
        TAG: "QA"
      with:
        host: ec2-3-23-123-190.us-east-2.compute.amazonaws.com
        username: ${{ secrets.AWS_USER_QA }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        envs: TAG
        script: | 
          sudo docker rm -f -v ui-gaming-cards
          sudo docker rmi -f $(sudo docker images 'jmgorduez/ui-gaming-cards' -q)
          sudo docker run -d -p 80:80 --network product-gallery-network --name ui-gaming-cards "jmgorduez/ui-gaming-cards:${TAG}"

    - name: Code checkout
      uses: actions/checkout@v2

    - name: Checking the deployment
      uses: cypress-io/github-action@v1
      with:
        spec: cypress/integration/testDeployQA.ispec.js
      
    - name: Slack Notification
      uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()
