name: Deploy to QA

on:
  push:
    branches: master 

jobs:
  deploy_to_QA_checker:
    name: Deploy to QA checker
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: NPM install -g yarn
      run: sudo npm install -g yarn  

    - name: YARN install, build
      run: |
        yarn
        yarn build

    - name: Running unit tests  
      run: |
        yarn test

  deploy_to_QA:
    name: Upload to AWS QA enviroment
    runs-on: ubuntu-latest
    needs: [deploy_to_QA_checker]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
          
    - name: Upload app images to the registry
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: jmgorduez/ui-gaming-cards
        tag: ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy app to AWS
      uses: appleboy/ssh-action@master
      env: 
        TAG: ${{ github.sha }}
      with:
        host: ${{ secrets.AWS_SERVER_QA }}
        username: ${{ secrets.AWS_USER_QA }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        envs: TAG
        script: | 
          docker rm -f -v ui-gaming-cards
          docker rmi -f $(sudo docker images 'jmgorduez/ui-gaming-cards' -q)
          docker run -d -p 80:80 --network product-gallery-network  -e PORT=80 --name ui-gaming-cards "jmgorduez/ui-gaming-cards:${TAG}"
      
    - name: Slack Notification
      uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()