name: Deploy to PRO

on:
  release:
    types: [published]
    branches: master 

jobs:
  deploy_to_PRO:
    name: Upload to AWS PRO enviroment
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
          
    - name: Upload app images to the registry
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: jmgorduez/ui-gaming-cards
        tag: ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: PRODUCT_GALLERY_MANAGER_URL=http://ec2-3-16-209-207.us-east-2.compute.amazonaws.com:8080/

    - name: Deploy app to AWS
      uses: appleboy/ssh-action@master
      env: 
        TAG: ${{ github.sha }}
      with:
        host: ec2-3-16-209-207.us-east-2.compute.amazonaws.com
        username: ${{ secrets.AWS_USER_PRO }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        envs: TAG
        script: | 
          docker rm -f -v ui-gaming-cards
          docker rmi -f $(sudo docker images 'jmgorduez/ui-gaming-cards' -q)
          docker run -d -p 80:80 --network product-gallery-network --name ui-gaming-cards "jmgorduez/ui-gaming-cards:${TAG}"
    
    - name: Checking the deployment
      uses: cypress-io/github-action@v1
      with:
        spec: cypress/integration/testDeployPRO.ispec.js

    - name: Slack Notification
      uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()
